name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Hostinger
        run: |
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
            # Clone or pull latest
            cd /var/www
            if [ ! -d vivavista_cicd_uk ]; then
              git clone https://github.com/StrixSid07/vivavista_cicd_uk.git
            fi
            cd vivavista_cicd_uk
            git fetch origin
            git reset --hard origin/main


            # Backend
            cd vivavistaukbackend
            npm install 
            pm2 stop vivavista-backend-uk || true
            pm2 start server.js --name vivavista-backend-uk
            pm2 save
            pm2 startup

            # Admin Panel
            cd ../vivavistaukadmin
            npm install
            npm run build
            rm -rf /var/www/vivavistaadminuk/*
            cp -r dist/* /var/www/vivavistaadminuk/

            # Main Website
            cd ../vivavistauk
            npm install
            npm run build
            rm -rf /var/www/vivavistauk/*
            cp -r dist/* /var/www/vivavistauk/
          EOF
